# Generated by Django 3.2.8 on 2021-11-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=5)),
                ('nama_barang', models.CharField(max_length=30)),
                ('jumlah', models.IntegerField()),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Terjual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=30)),
                ('kode_barang', models.CharField(max_length=5)),
                ('qtyterjual', models.IntegerField()),
                ('tglterjual', models.DateField()),
            ],
        ),
    ]
