# Generated by Django 3.2.8 on 2021-11-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasirapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
