# Generated by Django 3.2.8 on 2021-11-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasirapp', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tambah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=30)),
                ('kode_barang', models.CharField(max_length=5)),
                ('qtymasuk', models.IntegerField()),
                ('tglmasuk', models.DateField()),
            ],
        ),
    ]
